### ISSUE TITLE
Error when building Docker image

### ISSUE THREAD

**Issue by lukaszczerpak** [akamai/cli#95]
Docker image build throws the following error:

```
ARCH = amd64
OS = linux
Will install into /gopath/bin
Fetching https://github.com/golang/dep/releases/latest..
Release Tag = v0.5.4
Fetching https://github.com/golang/dep/releases/tag/v0.5.4..
Fetching https://github.com/golang/dep/releases/download/v0.5.4/dep-linux-amd64..
Setting executable permissions.
Moving executable to /gopath/bin/dep
# github.com/akamai/cli-common-golang
gopath/src/github.com/akamai/cli-common-golang/common.go:66:18: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
gopath/src/github.com/akamai/cli-common-golang/common.go:70:5: unknown field 'EnvVar' in struct literal of type cli.StringFlag
gopath/src/github.com/akamai/cli-common-golang/common.go:72:18: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
gopath/src/github.com/akamai/cli-common-golang/common.go:76:5: unknown field 'EnvVar' in struct literal of type cli.StringFlag
gopath/src/github.com/akamai/cli-common-golang/common.go:89:16: cannot use commands (type []cli.Command) as type []*cli.Command in assignment
gopath/src/github.com/akamai/cli-common-golang/common.go:92:18: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in assignment:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
gopath/src/github.com/akamai/cli-common-golang/common.go:97:25: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in assignment:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
gopath/src/github.com/akamai/cli-common-golang/common.go:101:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in assignment:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
gopath/src/github.com/akamai/cli-common-golang/common.go:145:12: cannot use ctx.App.Commands (type []*cli.Command) as type []cli.Command in assignment
gopath/src/github.com/akamai/cli-common-golang/common.go:149:13: cannot use ctx.Command.Subcommands (type []*cli.Command) as type []cli.Command in assignment
gopath/src/github.com/akamai/cli-common-golang/common.go:149:13: too many errors
```

I tried on Alpine 3.11 and 3.10 - same results.

**Comment by lukaszczerpak** [comment]
The following works on Alpine 3.11:

```
export GO111MODULE=auto
go get -d github.com/akamai/cli && cd $GOPATH/src/github.com/akamai/cli && go mod init && go mod tidy && go build -o /usr/local/bin/akamai
```

**Comment by lkowalsk-akamai-com** [comment]
We have now removed Dockerfile from this repository and as it is maintained else where. Please see Install with Docker section in README - https://github.com/akamai/cli#install-with-docker
